server:
  servlet:
    context-path: /finance/api
spring:
  profiles:
    active:
    - dev   
    
  datasource:
    hikari:      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 10
  jackson:    deserialization:      fail-on-unknown-properties: true   
      fail-on-ignored-properties: true 
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    
logging:
   file: ./log/finance.log
  