server:
  port: 80
  
spring:
  jpa:
    database: POSTGRESQL 
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false      
    show-sql: false
    hibernate:
      ddl-auto: validate       
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: '{JDBC_DATABASE_URL}'
    username: '{JDBC_DATABASE_USERNAME}'
    password: '{JDBC_DATABASE_PASSWORD}'

finances:
  security:
    enable-https: true
  origin-allow: 'http://localhost:8000'