server:
  servlet:
    context-path: /finance/api
spring:
  profiles:
    active:
    - dev
    
    
  datasource:
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
      test-on-borrow: true
      validation-query: SELECT 1
  jackson:    deserialization:      fail-on-unknown-properties: true   
      fail-on-ignored-properties: true 
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    
logging:
   file: ./log/finance.log
  